title: Zac Mann
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Zac Mann.
permalink: pretty
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.zacjrmann.com/" # the base hostname & protocol for your site, e.g. http://example.com

# Home banner settings
banner-video: mountains.mp4
banner-title: Welcome!
banner-desc: I made this.

# Author settings
author-name: Zac Mann
author-pic: abstract-colour.jpg
email: your-email@domain.com # your email
phone: (496)-169-6557 # your pnone number
website: https://dwayne.example.com # your website

# Social link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
facebook_url: https://www.facebook.com/profile.php?id=100006048617380
github_url: https://github.com/Toomber

# Disqus
discus_identifier: mr-brown # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

#sass directory
sass:
    sass_dir: assets/css/sass

#collections
collections:
  cats:
    output: true
    permalink: "/categories/:name/"

defaults:
  -
    scope:
      path: ""
      type: cats
    values:
      layout: category

plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["CNAME", "Gemfile", "Gemfile.lock", ".gitignore"]
